process.stdout.write("H");
 process.stdout.write("e");
  process.stdout.write("l");
   process.stdout.write("l");
    process.stdout.write("o");
      process.stdout.write(",");
      process.stdout.write(" ");
    process.stdout.write("W");
   process.stdout.write("o");
  process.stdout.write("r");
 process.stdout.write("l");
process.stdout.write("d\n");